apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # Number of Pods to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: spring-docker-container  # Name of the container
          image: ramugadde84/sample-docker-images:1.0  # The Docker image pushed to Docker Hub
          ports:
            - containerPort: 8080  # Port the container will expose

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: my-app-service
#spec:
#  selector:
#    app: my-app
#  ports:
#    - protocol: TCP
#      port: 9191          # Port exposed on the service (host)
#      targetPort: 8080    # Port on the container (application inside container)
#  type: NodePort      # Exposing via NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 9191  # Port on which the service is exposed
      targetPort: 8080  # Port the container is listening on
  type: LoadBalancer
